apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
  namespace: open-cluster-management-observability
spec:
  storageClassName: nutanix-block-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
